url: "https://hp-colombian-biodiversity.gbif-uat.org" # the base hostname & protocol for your staging site, e.g. https://hp-example.gbif-uat.org

useSharedLibrary: true # Use the new component library
testSite: true #style the site to show that it is a test site
graphqlEndpoint: "https://graphql.gbif-uat.org/graphql" # for use with e.g. new stories from GBIF.org